# Generated by Django 4.2.21 on 2025-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('theme_color', models.CharField(default='light', max_length=20)),
                ('font_size', models.CharField(default='medium', max_length=20)),
                ('layout', models.CharField(default='default', max_length=20)),
                ('profile_visible', models.BooleanField(default=True)),
                ('data_sharing', models.BooleanField(default=True)),
            ],
        ),
    ]
